# Starting with clean base image
FROM python:3.10

# Copy function code
COPY ./model/runner.py ./runner.py
COPY ./model/train.py ./train.py
COPY ./requirements.txt ./requirements.txt

RUN python3 -m pip install -r requirements.txt

# Set to call train.py
CMD [ "train" ]